# Generated by Django 4.0.3 on 2022-03-29 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('open_mouths', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('hearts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hearts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.userprofile')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_second_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('author_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.userprofile')),
                ('comentario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publicacion_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.userprofile'),
        ),
    ]
