# Generated by Django 4.0.3 on 2022-04-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_article_hearts_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hearts',
            new_name='hearts_amount',
        ),
        migrations.RemoveField(
            model_name='hearts',
            name='comment',
        ),
        migrations.AddField(
            model_name='hearts',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Articles.article'),
            preserve_default=False,
        ),
    ]
