# Generated by Django 4.0.3 on 2022-04-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_reactions_comments_2_reactions_comments_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions_comments_1',
            old_name='coment_1',
            new_name='coment',
        ),
        migrations.RenameField(
            model_name='reactions_comments_2',
            old_name='coment_2',
            new_name='coment',
        ),
    ]
